"""User table

Revision ID: 29af319bafda
Revises: cdba3659b7be
Create Date: 2020-04-20 21:12:00.980602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29af319bafda'
down_revision = 'cdba3659b7be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('state', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_user_state'), 'user', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_state'), table_name='user')
    op.drop_column('user', 'state')
    # ### end Alembic commands ###
