"""User table

Revision ID: cdba3659b7be
Revises: 1f1e70e3c7d5
Create Date: 2020-04-20 20:02:52.290012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdba3659b7be'
down_revision = '1f1e70e3c7d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_firstname', table_name='user')
    op.create_index(op.f('ix_user_firstname'), 'user', ['firstname'], unique=False)
    op.drop_index('ix_user_lastname', table_name='user')
    op.create_index(op.f('ix_user_lastname'), 'user', ['lastname'], unique=False)
    op.drop_index('ix_user_resumelink', table_name='user')
    op.create_index(op.f('ix_user_resumelink'), 'user', ['resumelink'], unique=False)
    op.drop_index('ix_user_sector', table_name='user')
    op.create_index(op.f('ix_user_sector'), 'user', ['sector'], unique=False)
    op.drop_index('ix_user_subcategory', table_name='user')
    op.create_index(op.f('ix_user_subcategory'), 'user', ['subcategory'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_subcategory'), table_name='user')
    op.create_index('ix_user_subcategory', 'user', ['subcategory'], unique=1)
    op.drop_index(op.f('ix_user_sector'), table_name='user')
    op.create_index('ix_user_sector', 'user', ['sector'], unique=1)
    op.drop_index(op.f('ix_user_resumelink'), table_name='user')
    op.create_index('ix_user_resumelink', 'user', ['resumelink'], unique=1)
    op.drop_index(op.f('ix_user_lastname'), table_name='user')
    op.create_index('ix_user_lastname', 'user', ['lastname'], unique=1)
    op.drop_index(op.f('ix_user_firstname'), table_name='user')
    op.create_index('ix_user_firstname', 'user', ['firstname'], unique=1)
    # ### end Alembic commands ###
